const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const VIN=/^[A-HJ-NPR-Z0-9]{17}$/;
const clean=v=>(v||'').trim().toUpperCase();function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
$('#menuBtn')?.addEventListener('click',()=>$('#mainNav').classList.toggle('open'));
$('#vinForm')?.addEventListener('submit',e=>{e.preventDefault();const v=clean($('#vin').value);if(!VIN.test(v))return toast('Enter a valid 17-character VIN.');$('#orderVin').value=v;document.querySelector('#pricing').scrollIntoView({behavior:'smooth'});toast('VIN accepted. Choose a paid report to continue.');});
$$('.select-plan').forEach(b=>b.addEventListener('click',()=>{$('#plan').value=b.dataset.plan;document.querySelector('#order').scrollIntoView({behavior:'smooth'});}));
$('#orderForm')?.addEventListener('submit',e=>{e.preventDefault();const v=clean($('#orderVin').value);if(!VIN.test(v))return toast('Enter a valid 17-character VIN.');if(!$('#agree').checked)return toast('Please accept the legal terms.');$('#orderMsg').textContent='Checkout demo only. No payment was processed and no vehicle-specific data was released.';toast('Ready for payment connection.');});
function reply(q){const s=q.toLowerCase();if(/[A-HJ-NPR-Z0-9]{17}/i.test(q))return 'Vehicle-specific VIN findings are available only inside a purchased report.';if(s.includes('recall'))return 'A recall is a manufacturer safety campaign. NYC Auto Pro includes vehicle-specific recall findings inside paid reports; official status should still be confirmed with NHTSA or the manufacturer.';if(s.includes('inspect'))return 'A pre-purchase inspection should cover warning lights, leaks, tires, brakes, suspension, electronics, body repairs and underbody condition.';if(s.includes('title')||s.includes('lien'))return 'Verify the seller name, VIN, title brands and liens before payment using official or licensed sources.';if(s.includes('negoti')||s.includes('price'))return 'Compare similar vehicles by year, trim, mileage, condition and history, then use documented issues as negotiation points.';if(s.includes('seller'))return 'Ask about ownership, maintenance, collision repairs, title status, liens, warning lights and whether an independent inspection is allowed.';return 'I can explain how NYC Auto Pro works and give general used-car buying guidance. Vehicle-specific findings stay inside paid reports.'}
function add(t,w='bot'){const d=document.createElement('div');d.className=w;d.textContent=t;$('#msgs').appendChild(d);$('#msgs').scrollTop=$('#msgs').scrollHeight}
function ask(q){add(q,'user');setTimeout(()=>add(reply(q),'bot'),220)}
$$('.aiq').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#ai').scrollIntoView({behavior:'smooth'});setTimeout(()=>ask(b.dataset.q),300)}));
$('#chatForm')?.addEventListener('submit',e=>{e.preventDefault();const q=$('#chatInput').value.trim();if(!q)return;$('#chatInput').value='';ask(q)});
$('#floatHelp')?.addEventListener('click',()=>document.querySelector('#ai').scrollIntoView({behavior:'smooth'}));